spring.mongodb.uri=${MONGODB_URI}
logging.level.org.springframework.web=DEBUG
app.security.jwt.secret=${JWT_SECRET}
app.security.jwt.expiration-ms=${JWT_EXPIRATION_MS}
<<<<<<< HEAD
app.security.order-access-secret=${ORDER_ACCESS_SECRET:${JWT_SECRET}}
app.cors.allowed-origin-patterns=${APP_CORS_ALLOWED_ORIGIN_PATTERNS}
=======
app.cors.allowed-origin-patterns=${APP_CORS_ALLOWED_ORIGIN_PATTERNS:http://localhost:5173,http://127.0.0.1:5173}
google.maps.api-key=${GOOGLE_MAPS_API_KEY}
>>>>>>> 5f56ce829bc12a91f2d6f4314131ed60cf49bd31
logging.level.org.hibernate=DEBUG
spring.web.error.include-stacktrace=always
spring.web.error.include-message=always
