spring.mongodb.uri=${MONGODB_URI}
logging.level.org.springframework.web=DEBUG
app.security.jwt.secret=${JWT_SECRET}
app.security.jwt.expiration-ms=${JWT_EXPIRATION_MS}
logging.level.org.hibernate=DEBUG
spring.web.error.include-stacktrace=always
spring.web.error.include-message=always
